### ISSUE TITLE
Difference between this and the original version and Page's version

### ISSUE THREAD

**Issue by CMCDragonkai** [xixixao/meta-coffee#6]
I've been looking at the different forks of OMeta since Alex doesn't maintain the original anymore.

In terms of features would you be able to sum up the difference between this, original and Page's version: https://github.com/Page-/ometa-js

Of course this one is in Coffeescript.

**Comment by xixixao** [comment]
I can't tell what the additions in Page-'s version are. I did try fedor's version, and I did try to ask him in which ways his version differed (https://twitter.com/search?f=realtime&q=indutny%20xixixao&src=typd). As far as I remember I stuck pretty much to the original, I don't think there are significant changes in terms of features. I added the token position as I needed it in a compiler implementation, but I assume you could do the same in OMeta.
